#!/usr/bin/env bash

echo "A aplicar motd... Por favor, aguarde."
wget https://raw.githubusercontent.com/djprmf/centos-change-motd/master/motd
bash motd

echo "A aplicar hostname... Por favor, aguarde."
wget https://raw.githubusercontent.com/djprmf/centos-change-hostname/master/hostname6
bash hostname6

echo "Tarefas concluidas com sucesso"
echo "Por favor, reinicie o sistema."
